# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

build:
  stage: build
  variables:
    Dockerfile: v0.14/debian
    ImageTag: "v0.14/debian-${CI_COMMIT_REF_SLUG}.${CI_PIPELINE_ID}.${CI_JOB_ID}"
    ImageName: "${CI_REGISTRY_IMAGE}
  script:
    - apk update
    - apk add make
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - make image DOCKERFILE=$Dockerfile VERSION=$ImageTag || sleep 999999
    - docker tag fluent/fluentd:${ImageTag} ${ImageName}:${ImageTag}
    - echo make test DOCKERFILE=$Dockerfile VERSION=$ImageTag || sleep 999999
    - docker push "${ImageName}:${ImageTag}"
