# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

build:
  stage: build
  variables:
    Dockerfile: v0.14/debian
    ImageTag: "${CI_COMMIT_REF_SLUG}.${CI_PIPELINE_ID}.${CI_JOB_ID}"
    ImageName: "${CI_REGISTRY_IMAGE}/v0.14/debian"
  script:
    - apk update
    - apk add make
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - make image DOCKERFILE=$Dockerfile VERSION=$ImageTag || sleep 999999
    - docker images | head -5
    - docker tag fluentd/fluentd:${ImageTag} ${ImageName}:${ImageTag}
    - echo make test DOCKERFILE=$Dockerfile VERSION=$ImageTag || sleep 999999
    - sleep 999999
    - echo docker build --pull -t "$CI_REGISTRY_IMAGE:$ImageTag" .
    - docker push "$CI_REGISTRY_IMAGE:$ImageTag"
